### ISSUE TITLE
Estructura generación

### ISSUE THREAD

**Issue by silenciosonoro** [JorgeGT/getREEdata#1]
Hola,

Estoy intentando realizar un script para descargar de forma diaria la estructura de generación.
¿Tienes el script que usas para Matlab para VBA?

Gracias de antemano.

**Comment by JorgeGT** [comment]
Hola, me temo que no (nunca he sido de Visual Basic!). Pero básicamente es leer un archivo de texto en formato JSON de 

`https://demanda.ree.es/WSvisionaMovilesPeninsulaRest/resources/demandaGeneracionPeninsula?callback=angular.callbacks._2&curva=DEMANDA&fecha=2016-02-09` 

Cambiando la fecha según el día. Supongo que en VBA habrá funciones para leer desde web un archivo de texto y convertir JSON a una tabla? 

Siento no poder ayudarte más!

**Comment by silenciosonoro** [comment]
Sí sí. Estoy en ello.
Muchas gracias.
